### PR TITLE
Release 1.13.0

### PR DESCRIPTION
**Pull request by dryewo**
Include swagger1st 0.24.0

### CODE REVIEW

**Comment by dryewo** [comment]
👍

**Comment by dryewo** [comment]
:

**Comment by dryewo** [comment]
👍

**Comment by dryewo** [comment]
Available at: http://repo1.maven.org/maven2/org/zalando/stups/friboo/1.13.0/

**Comment by sebastianpoeplau** [comment]
👍

**Comment by dryewo** [comment]
👍

**Pull request merged**
