### PR TITLE
add an 'enabled' field to the audit_logger when it is created

### PR DESCRIPTION
**Pull request by kolja**

### CODE REVIEW

**Comment by kolja** [comment]
👍

**Comment by sebastianpoeplau** [comment]
@kolja, would it make sense to add a check for `:enabled` to the `log` function?

**Comment by kolja** [comment]
@sebastianpoeplau yes, I'll change it...

**Comment by sebastianpoeplau** [comment]
As discussed on Wednesday, here's some more detail on my suggestions regarding the log function: Ideally, I think there should be a function in the `friboo.system.audit-logger.http` namespace that takes the logger component as its first argument, so that one could use it as follows:

```clojure
(ns my-awesome-component
  (:require [friboo.system.audit-logger.http :as audit])
  ...)

(defn whatever [& args]
  ...
  (audit/log my-audit-logger-instance "Yay, success!"))
```

This is, of course, a breaking change. I think the transition to Friboo 2.0 is a good time for it, but if we wanted to stick with the old approach of having the log function available under some key `:log-fn` in the logger component, we could make sure that there is always a function that can be called:

```clojure
(defn fake-log [msg]
  (log/warn "The audit logger has not been started!"))

;; Users of this component would call this constructor to initialize the HTTP record.
(defn make-http []
  (map->HTTP {:log-fn fake-log})

;; The HTTP record's stop method would reset :log-fn to fake-log after stopping the component.
```

I don't like this latter approach, but it would retain backward compatibility while making it safe to use the audit log function on a stopped component, which seems to be the overall goal of this PR.

**Comment by dryewo** [comment]
As audit logging is going to move to friboo-ext-zalando, here is this PR: https://github.com/zalando-incubator/friboo-ext-zalando/pull/7

**Comment by dryewo** [comment]
Will be available in friboo-ext-zalando soon.

**Pull request closed without merging**
