### PR TITLE
Add handler wrapper utility function.

### PR DESCRIPTION
**Pull request by dryewo**
Example usage:

``` clj
(defn get-status
  "Return status information."
  [params request]
  (with-json-handler
    (response {:version    (implementation-version)
               :status     :ok})))

```

### CODE REVIEW

**Comment by hjacobs** [comment]
Why do we need this? Friboo/Swagger1st automatically serializes JSON if "produces" is set correctly IIRC.

**Comment by dryewo** [comment]
I just tried, it throws `java.lang.Exception: Unrecognized body`.
I use this wrapper for 2 reasons:
1. JSON content type
2. Exception wrapping to produce nice HTTP 500 responses

**Comment by hjacobs** [comment]
Hmm, does not convince me yet :smirk:

**Comment by hjacobs** [comment]
I guess @prayerslayer or @sarnowski could have a look.

**Comment by prayerslayer** [comment]
I agree this should be done automatically somewhere and not part of the application code. Seems like a Swagger1st issue?

**Pull request closed without merging**
